<?php

namespace Database\Seeders;

use App\Models\Wallet;
use App\Models\WalletTransaction;
use Illuminate\Database\Seeder;

class WalletSeeder extends Seeder
{
    public function run(): void
    {
        $wallet = Wallet::create([
            'name' => 'Demo Portfolio',
            'address' => '0xDemoWallet123456789'
        ]);

        $transactions = [
            ['date' => '2024-01-15', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.01, 'price_per_unit_zar' => 850000.0, 'total_value_zar' => 8500.0, 'fees_zar' => 50.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN001', 'notes' => 'Initial BTC purchase', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-02-02', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.5, 'price_per_unit_zar' => 45000.0, 'total_value_zar' => 22500.0, 'fees_zar' => 120.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN002', 'notes' => 'ETH accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-03-01', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.005, 'price_per_unit_zar' => 920000.0, 'total_value_zar' => 4600.0, 'fees_zar' => 40.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN003', 'notes' => 'Partial BTC sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-03-18', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.3, 'price_per_unit_zar' => 47000.0, 'total_value_zar' => 14100.0, 'fees_zar' => 80.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN004', 'notes' => 'Market dip buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-03-25', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 10.0, 'price_per_unit_zar' => 2800.0, 'total_value_zar' => 28000.0, 'fees_zar' => 150.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN005', 'notes' => 'SOL entry', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-04-02', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.004, 'price_per_unit_zar' => 880000.0, 'total_value_zar' => 3520.0, 'fees_zar' => 30.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN006', 'notes' => 'DCA BTC', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-04-10', 'type' => 'sell', 'asset' => 'ETH', 'quantity' => 0.2, 'price_per_unit_zar' => 52000.0, 'total_value_zar' => 10400.0, 'fees_zar' => 60.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN007', 'notes' => 'ETH profit taking', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-04-15', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 2000.0, 'price_per_unit_zar' => 9.5, 'total_value_zar' => 19000.0, 'fees_zar' => 100.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN008', 'notes' => 'ADA accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-04-22', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.003, 'price_per_unit_zar' => 895000.0, 'total_value_zar' => 2685.0, 'fees_zar' => 25.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN009', 'notes' => 'DCA BTC', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-05-01', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.4, 'price_per_unit_zar' => 50000.0, 'total_value_zar' => 20000.0, 'fees_zar' => 110.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN010', 'notes' => 'ETH buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-05-05', 'type' => 'sell', 'asset' => 'SOL', 'quantity' => 4.0, 'price_per_unit_zar' => 3100.0, 'total_value_zar' => 12400.0, 'fees_zar' => 70.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN011', 'notes' => 'SOL partial sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-05-12', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.0025, 'price_per_unit_zar' => 910000.0, 'total_value_zar' => 2275.0, 'fees_zar' => 20.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN012', 'notes' => 'BTC DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-05-20', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1500.0, 'price_per_unit_zar' => 10.2, 'total_value_zar' => 15300.0, 'fees_zar' => 90.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN013', 'notes' => 'ADA add', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-05-28', 'type' => 'sell', 'asset' => 'ETH', 'quantity' => 0.15, 'price_per_unit_zar' => 54000.0, 'total_value_zar' => 8100.0, 'fees_zar' => 50.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN014', 'notes' => 'ETH trim', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-06-03', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 8.0, 'price_per_unit_zar' => 2950.0, 'total_value_zar' => 23600.0, 'fees_zar' => 120.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN015', 'notes' => 'SOL add', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-06-10', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.002, 'price_per_unit_zar' => 930000.0, 'total_value_zar' => 1860.0, 'fees_zar' => 15.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN016', 'notes' => 'BTC DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-06-18', 'type' => 'sell', 'asset' => 'ADA', 'quantity' => 700.0, 'price_per_unit_zar' => 11.5, 'total_value_zar' => 8050.0, 'fees_zar' => 45.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN017', 'notes' => 'ADA profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-06-25', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.35, 'price_per_unit_zar' => 51500.0, 'total_value_zar' => 18025.0, 'fees_zar' => 95.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN018', 'notes' => 'ETH buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-07-01', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.003, 'price_per_unit_zar' => 945000.0, 'total_value_zar' => 2835.0, 'fees_zar' => 25.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN019', 'notes' => 'DCA BTC', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-07-08', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 6.0, 'price_per_unit_zar' => 3050.0, 'total_value_zar' => 18300.0, 'fees_zar' => 90.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN020', 'notes' => 'SOL add', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-07-15', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.002, 'price_per_unit_zar' => 980000.0, 'total_value_zar' => 1960.0, 'fees_zar' => 20.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN021', 'notes' => 'BTC sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-07-22', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1800.0, 'price_per_unit_zar' => 10.8, 'total_value_zar' => 19440.0, 'fees_zar' => 110.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN022', 'notes' => 'ADA accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-07-30', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.25, 'price_per_unit_zar' => 53000.0, 'total_value_zar' => 13250.0, 'fees_zar' => 70.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN023', 'notes' => 'ETH DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-08-05', 'type' => 'sell', 'asset' => 'SOL', 'quantity' => 5.0, 'price_per_unit_zar' => 3300.0, 'total_value_zar' => 16500.0, 'fees_zar' => 85.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN024', 'notes' => 'SOL profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-08-12', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.0028, 'price_per_unit_zar' => 960000.0, 'total_value_zar' => 2688.0, 'fees_zar' => 25.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN025', 'notes' => 'BTC DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-08-20', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.3, 'price_per_unit_zar' => 54500.0, 'total_value_zar' => 16350.0, 'fees_zar' => 85.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN026', 'notes' => 'ETH buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-08-28', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1600.0, 'price_per_unit_zar' => 11.2, 'total_value_zar' => 17920.0, 'fees_zar' => 95.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN027', 'notes' => 'ADA add', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-09-02', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.0015, 'price_per_unit_zar' => 1000000.0, 'total_value_zar' => 1500.0, 'fees_zar' => 15.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN028', 'notes' => 'BTC profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-09-10', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 7.0, 'price_per_unit_zar' => 3200.0, 'total_value_zar' => 22400.0, 'fees_zar' => 110.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN029', 'notes' => 'SOL buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-09-18', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.4, 'price_per_unit_zar' => 56000.0, 'total_value_zar' => 22400.0, 'fees_zar' => 120.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN030', 'notes' => 'ETH accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-09-25', 'type' => 'sell', 'asset' => 'ADA', 'quantity' => 900.0, 'price_per_unit_zar' => 12.5, 'total_value_zar' => 11250.0, 'fees_zar' => 60.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN031', 'notes' => 'ADA sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-10-01', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.0032, 'price_per_unit_zar' => 985000.0, 'total_value_zar' => 3152.0, 'fees_zar' => 30.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN032', 'notes' => 'DCA BTC', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-10-08', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 9.0, 'price_per_unit_zar' => 3400.0, 'total_value_zar' => 30600.0, 'fees_zar' => 150.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN033', 'notes' => 'SOL buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-10-15', 'type' => 'sell', 'asset' => 'ETH', 'quantity' => 0.2, 'price_per_unit_zar' => 59000.0, 'total_value_zar' => 11800.0, 'fees_zar' => 65.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN034', 'notes' => 'ETH profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-10-22', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1400.0, 'price_per_unit_zar' => 12.0, 'total_value_zar' => 16800.0, 'fees_zar' => 90.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN035', 'notes' => 'ADA buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-11-01', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.0025, 'price_per_unit_zar' => 1020000.0, 'total_value_zar' => 2550.0, 'fees_zar' => 25.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN036', 'notes' => 'BTC DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-11-08', 'type' => 'sell', 'asset' => 'SOL', 'quantity' => 6.0, 'price_per_unit_zar' => 3600.0, 'total_value_zar' => 21600.0, 'fees_zar' => 110.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN037', 'notes' => 'SOL sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-11-15', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.35, 'price_per_unit_zar' => 57500.0, 'total_value_zar' => 20125.0, 'fees_zar' => 100.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN038', 'notes' => 'ETH buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-11-22', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1200.0, 'price_per_unit_zar' => 12.8, 'total_value_zar' => 15360.0, 'fees_zar' => 85.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN039', 'notes' => 'ADA add', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-01', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.002, 'price_per_unit_zar' => 1050000.0, 'total_value_zar' => 2100.0, 'fees_zar' => 20.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN040', 'notes' => 'BTC profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-05', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 8.0, 'price_per_unit_zar' => 3550.0, 'total_value_zar' => 28400.0, 'fees_zar' => 140.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN041', 'notes' => 'SOL accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-10', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.3, 'price_per_unit_zar' => 59000.0, 'total_value_zar' => 17700.0, 'fees_zar' => 90.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN042', 'notes' => 'ETH DCA', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-15', 'type' => 'sell', 'asset' => 'ADA', 'quantity' => 1000.0, 'price_per_unit_zar' => 13.5, 'total_value_zar' => 13500.0, 'fees_zar' => 70.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN043', 'notes' => 'ADA sell', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-20', 'type' => 'buy', 'asset' => 'BTC', 'quantity' => 0.003, 'price_per_unit_zar' => 1080000.0, 'total_value_zar' => 3240.0, 'fees_zar' => 30.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN044', 'notes' => 'Year-end BTC buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-24', 'type' => 'buy', 'asset' => 'ETH', 'quantity' => 0.4, 'price_per_unit_zar' => 60000.0, 'total_value_zar' => 24000.0, 'fees_zar' => 130.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN045', 'notes' => 'Year-end ETH buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-27', 'type' => 'buy', 'asset' => 'SOL', 'quantity' => 10.0, 'price_per_unit_zar' => 3700.0, 'total_value_zar' => 37000.0, 'fees_zar' => 180.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN046', 'notes' => 'SOL accumulation', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-29', 'type' => 'sell', 'asset' => 'ETH', 'quantity' => 0.25, 'price_per_unit_zar' => 62000.0, 'total_value_zar' => 15500.0, 'fees_zar' => 80.0, 'exchange' => 'Luno', 'transaction_id' => 'TXN047', 'notes' => 'ETH profit', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-30', 'type' => 'buy', 'asset' => 'ADA', 'quantity' => 1500.0, 'price_per_unit_zar' => 13.0, 'total_value_zar' => 19500.0, 'fees_zar' => 100.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN048', 'notes' => 'ADA year-end buy', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2024-12-31', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.0018, 'price_per_unit_zar' => 1100000.0, 'total_value_zar' => 1980.0, 'fees_zar' => 18.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN049', 'notes' => 'Portfolio rebalance', 'acquired_asset' => null, 'acquired_quantity' => null],
            ['date' => '2025-01-02', 'type' => 'sell', 'asset' => 'BTC', 'quantity' => 0.08, 'price_per_unit_zar' => 1090000.0, 'total_value_zar' => 87200.0, 'fees_zar' => 22.0, 'exchange' => 'Binance', 'transaction_id' => 'TXN050', 'notes' => 'New year BTC Sell', 'acquired_asset' => null, 'acquired_quantity' => null],
        ];

        foreach ($transactions as $tx) {
            $tx['wallet_id'] = $wallet->id;
            WalletTransaction::create($tx);
        }
    }
}
